base_image: null
bundled_packages_dir: packages
data_dir: data
description: An instruction-following LLM Using Evol-Instruct.
environment_variables: {}
examples_filename: examples.yaml
external_package_dirs: []
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata:
  example_model_input: {"prompt": "What is the difference between a wizard and a sorcerer?"}
  avatar_url: https://cdn.baseten.co/production/static/explore/wizard.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/wizardlm.png
  tags:
  - text-generation
model_module_dir: model
model_name: WizardLM
model_type: custom
python_version: py39
requirements:
- accelerate==0.20.3
- bitsandbytes==0.39.1
- peft==0.3.0
- protobuf==4.23.3
- sentencepiece==0.1.99
- torch==2.0.1
- transformers==4.30.2
resources:
  cpu: "3"
  memory: 14Gi
  use_gpu: true
  accelerator: A10G
secrets: {}
spec_version: '2.0'
system_packages: []
